@address = http://localhost:8000

###

POST  {{address}}/sd/callback
Content-Type:  application/json

{
  "signature":"ea31eaa36d4dc631e7f7fe369b7bd101ed12e8e1",
  "appid":"appId",
  "timestamp":1765362687303,
  "nonce":"CoqtKGfz4YPPg94U",
  "encrypt":"VTF1MICA7OUOt8siRSrEKZl/5hdPtRnAdSdO+PtdDMrpg0S9jYauLudlYyPnyismH7FyJdpK1PM5zn06IcKMntWleIIcjasxYQytlhuvq1fNfhqNw6g1c7RHEwbN6FC25+plVF7z1OHUNNbGsvpaTtlvyLIy7Y7+mcbWjla72Tu3zffm6xeZBMgP1XCpH/ZNofuD+Z2Ivrj/6sdNsD4zaXGdTEvT+O+SHj9lv3rRbOuPhIkYJ9ufrHBMtXVyoyjWLpUoU+KIQ/3wBcRXMhYkqfIBIxi5vfj5kcjb5A1xO36dioE7UlwRq+0DE7DSBTLUd9pPR4m5DbBBZ/tTlKQ9dMo0KxyUTHL7yvD7pGyDOfYEk/EX8Ho9+IZEBwfaVjeqVIYc315W23UCTdu7pgq0tZr5ndaryM+dDAnk112S6ws="
}
